
# -*- coding: utf-8 -*-
#+TITLE: harte echtzeit - sonic experiments

** [[./logo-HE_no_bg.svg]] 
harte echtzeit (HE) is a scientist and sonic artist who works with  algortihms, scientific data and live coding.

HE's interest is mainly in the interplay of abstract sounds and concrete, rhythmic structures. his music is driven by scientific data which seems to have no history or imagination on a human scale but rather on larger more complex scales in space and time. capturing the vast journey, time and energy which encompasses events that, for example emit gravitational waves, while also finding ways to communicate about it in a human scale language, plays a central role in HE's work. as a result, it leads to compositions which explore and experiment with sounds and soundscapes but also let rhythmic or melodic structures sneek in from time to time.  

he is currently based in Melbourne, Australia and loosely connected to German and Spanish live coding hubs. he is one co-founder of [[https://futur-aaa.com/][futur AAA festival]] and organizes algoraves,
workshops and other events himself.
** =>sonic experiments
*** gravitational waves
it took about 100 years for Einsteins prediction to become true, but in 2015 gravitational waves were detected for the first time by the [[https://advancedligo.mit.edu/][Advanced LIGO]] instrument. these waves coming from the depths of space, carry energy and information about the history of the universe and hit us on a daily basis. with my project [[https://github.com/harte-echtzeit/the_gw_ep][Gravitational Wave Field Recordings (GWFR)]], I use audio samples of detected gravitational waves and transform them into musique concréte-inspired pieces of sonic art. by utilizing techniques of live coding, I perform music with computer code which conveys the history of gravitational wave detection and the deep space. the music helps us to travel through space and time with rhythmic patterns, mysterious sound textures and experimental structures. the tracks explore space and time in a minimal yet sometimes dreamy as well as danceble way.

a set of tracks was released as the album [[https://callitanythingrecords.bandcamp.com/album/ji-k-kan][ji kū kan]] on September 14th, 2024 via [[https://callitanythingrecords.bandcamp.com/][Call It Aything Records]]. it is available digitally and as a limited edition cassette tape. a press release for this album can be download [[file:~/programmierung/harte_echtzeit/he_website/public/pm_text.pdf][here]].

some tracks of the album were featured in radio shows and discussed in blogs [[[https://rdl.de/beitrag/schrill-09022024][1]], [[https://www.nts.live/shows/fractalmeat/episodes/fractalmeat-1st-october-2024][2]], [[https://acloserlisten.com/2024/09/04/fall-music-preview-2024-experimental/][3]]]. especially, [[https://audiocrackle.blogspot.com/2024/10/non-music-roundup-oct-24.html][AUDIO CRACKLE]] praises it for its uniqueness
 #+BEGIN_QUOTE
 'ji kū kan' is an atmospheric album of cosmic soundscapes - filled with demented "dance" rhythms, erratic pulsations, minimal techno, mesmerizing drones and experimental musique concrète. I can't claim to understand the technicalities of live coding, or how these compositions were created... but I can definitely appreciate the uniqueness of it, and enjoy this abstract aural adventure! An unnerving yet trance-inducing listening experience.
 #+END_QUOTE

*** what is a nanoloop?
[[https://nanoloop.com/][nanoloop]] is a neat and minimal graphic step sequencer for the Gameboy plattform written by Oliver Wittchow. many thanks to oliver for the tool.

currently, I'm exploring what a ~nanoloop~ means and how I want to work with it. some tracks are written and might get recorded soon.

** =>live
- 2025-06-01 *ji kū kan* gig @ [[https://iclc.toplap.org/2025/][ICLC 2025]] post-conference show, [[https://www.niubcn.com/][niu : espai artístic contemporani]], Barcelona, Spain
- 2025-02-01 /*ji kū kan*/ jam session @ Corvallis/OR, USA
- 2025-01-31 /*ji kū kan*/ gig and talk @ [[https://www.ligo.caltech.edu/WA/page/lho-tours-and-events][LIGO]] Observatory Hanford/WA, USA 
- 2024-09-20 /*ji kū kan*/ release party @ [[http://itr.root.sx/upcoming/2024-09-20][Pracht]], Leipzig/DE
- 2024-09-07 talk and gig @ [[https://www.werkraum.space/wiki/ckg:start][10 Jahre Polytechnischer Werkraum]], Zittau/DE
- 2024-08-31 GW live set during [[https://www.hannover.de/Kultur-Freizeit/Museen-Ausstellungen/Bildende-Kunst/ZINNOBER][Zinnober]] @ Atelier [[http://meike-zopf.de/][Meike Zopf]] ([[https://www.eisfabrik.com/][Eisfabrik]]), Hannover/DE
- 2024-08-31 show&tell of GW music @ [[https://www.geo600.org/openday24][OpenDay]] at GEO600 Gravitational-wave detector, Hannover/DE
- 2024-06-21 together with my friend MC Algorhythm as /Glitchcore Brüder/ @ Fête de la Musique Zwickau/DE
- 2024-06-14->16 [[https://futur-aaa.com/][futur AAA]], live coding festival, organizer, Zwickau/DE
- 2024-05-25 GW live set @ Toplap Asia ICLC stream, online [[[https://archive.org/details/toplap-asia-may2024-harte-echtzeit][video]]]
- 2024-04-20 GW live set @ VIU festival, Sala Vol, Barcelona/ES [[[https://www.youtube.com/watch?v=xAdQEg-Alf8][video]]]
- 2024-03-30 jaming GW @ z-Labor hackerspace Zwickau/DE
- 2024-02-23 GW live set @ Toplap20 stream, online [[[https://youtu.be/U2xDSY_8VwE?feature=shared][video]]]
- 2024-02-09 radio appearence with Track GWFR01 @ /Schrill/ radio show on Radio Dreyeckland [[[https://rdl.de/beitrag/schrill-09022024][recording]]] 
- 2023-12-12 experiments with ORCA and audience @ X-mas Beats'n'bits algorave, Zwickau/DE
- 2023-05-19 together with my friend MC Algorhythm as /Glitchcore Brüder/ @ Critical Rave, Seilerstraße Zwickau/DE
- 2023-04-30 together with my friend MC Algorhythm as /Glitchcore Brüder/ @ Viele Wege Festival, Kunstverein Freunde Aktueller Kunst, Zwickau/DE
- 2022-08-26 sonic experiments solo and with my friend MC Algorhythm as /Glitchcore Brüder/ @ Nerd Arts Night, Kunstplantage Zwickau/DE [[[https://youtu.be/lfmEnMnQT3M?feature=shared][video solo]], [[https://youtu.be/ioDOdGKDp6I?feature=shared][video 2gether]]]

** =>tools
   from time to time, I develop small tools with regards to music and art. feel free to play with them.
*** not-a-notation
This is a notation for Tidal Cycles which helps me to write tracks for live playing and recording without taking away the live coding part. it is designed to work on paper and as a plain-text file which uses the ending =.nan=. please find it on in this [[https://github.com/harte-echtzeit/not-a-notation][repository]].

** =>contact & connections
+ booking and questions: =info[at]harte-echtzeit.com= 
+ plattforms:
  - [[https://github.com/harte-echtzeit][github]]
  - [[https://sonomu.club/@harte_echtzeit][mastodon]]
  - [[https://www.instagram.com/harte_echtzeit/][Instagram]]
+ [[https://www.instagram.com/mc_algorhythm?igsh=ZmE5MWpyNTA0ZzVj][MC Algorhythm]] is my partner-in-crime in our  project /Glitchcore Brüder/
+ [[https://futur-aaa.com/][futur AAA]] is a live coding festival, I co-organize.
+ [[https://callitanythingrecords.bandcamp.com/][Call It Aything Records]] is the label I release with.
